"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

APP = ['main.py']
DATA_FILES = [('', ['resources']), ('', ['helper']), ('', ['modules']), ('', ['constants.py'])]


OPTIONS = {'iconfile':'main.icns',
           'packages': ['pygame'],
           'argv_emulation': True,
           'semi_standalone' : False}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
